### ISSUE TITLE
FormList changes can potentially affect other mods in an unintended manner.

### ISSUE THREAD

**Issue by BeranabusBarnes** [tmpbased/SynSpellTomeFreeLeveledLists#1]
While removing some spell tome distribution, FormList changes can seemingly cause issues for other mods that use lists of spell tomes for different purposes. An ability to blacklist plugins would help alleviate the issue.

**Comment by tmpbased** [comment]
You are correct.
Added some configuration options to blacklist plugins or to avoid touching FormLists altogether.
